jms_security_extra:
    secure_all_services:                    false
    expressions:                            true

security:
    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, fos_userbundle]
        fos_userbundle:
            id:                             fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    admin:
                        password:           admin,
                        roles:              ['ROLE_ADMIN']

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:                         ROLE_USER
        ROLE_SUPER_ADMIN:                   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:                        ^/(_(profiler|wdt)|css|images|js)/
            security:                       false

        main:
            pattern:                        ^/
            form_login:
                provider:                   chain_provider
                csrf_provider:              form.csrf_provider
            logout:                         true
            anonymous:                      true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
